//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTTLanguages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTTLanguages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Labs.
        /// </summary>
        public static string AllLabs {
            get {
                return ResourceManager.GetString("AllLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Samples.
        /// </summary>
        public static string AllSamples {
            get {
                return ResourceManager.GetString("AllSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sponsors.
        /// </summary>
        public static string AllSponsors {
            get {
                return ResourceManager.GetString("AllSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyst.
        /// </summary>
        public static string Analyst {
            get {
                return ResourceManager.GetString("Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve All.
        /// </summary>
        public static string ApproveAll {
            get {
                return ResourceManager.GetString("ApproveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Line.
        /// </summary>
        public static string BusinessLine {
            get {
                return ResourceManager.GetString("BusinessLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel / Refresh.
        /// </summary>
        public static string CancelRefresh {
            get {
                return ResourceManager.GetString("CancelRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAR.
        /// </summary>
        public static string CAR {
            get {
                return ResourceManager.GetString("CAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAR Breakdown.
        /// </summary>
        public static string CARBreakdown {
            get {
                return ResourceManager.GetString("CARBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAR Response.
        /// </summary>
        public static string CARResponse {
            get {
                return ResourceManager.GetString("CARResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Lab Summary.
        /// </summary>
        public static string CompanyLabSummary {
            get {
                return ResourceManager.GetString("CompanyLabSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Performance Summary Report.
        /// </summary>
        public static string CompanyPerformanceSummaryReport {
            get {
                return ResourceManager.GetString("CompanyPerformanceSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Action Request.
        /// </summary>
        public static string CorrectiveActionRequest {
            get {
                return ResourceManager.GetString("CorrectiveActionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Administration Dashboard.
        /// </summary>
        public static string DataAdminDashboard {
            get {
                return ResourceManager.GetString("DataAdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User Dashboard.
        /// </summary>
        public static string DefaultUserDashboard {
            get {
                return ResourceManager.GetString("DefaultUserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Manager.
        /// </summary>
        public static string DivisionManager {
            get {
                return ResourceManager.GetString("DivisionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNR.
        /// </summary>
        public static string DNR {
            get {
                return ResourceManager.GetString("DNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled Programs.
        /// </summary>
        public static string EnrolledPrograms {
            get {
                return ResourceManager.GetString("EnrolledPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string Enrollment {
            get {
                return ResourceManager.GetString("Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments By Location.
        /// </summary>
        public static string EnrollmentbyLocation {
            get {
                return ResourceManager.GetString("EnrollmentbyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments By Program.
        /// </summary>
        public static string EnrollmentByProgram {
            get {
                return ResourceManager.GetString("EnrollmentByProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments.
        /// </summary>
        public static string Enrollments {
            get {
                return ResourceManager.GetString("Enrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Summary.
        /// </summary>
        public static string EnrollmentSummary {
            get {
                return ResourceManager.GetString("EnrollmentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Word.
        /// </summary>
        public static string ExportToWord {
            get {
                return ResourceManager.GetString("ExportToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ - Frequently Asked Questions.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-CAR.
        /// </summary>
        public static string FCAR {
            get {
                return ResourceManager.GetString("FCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade History.
        /// </summary>
        public static string GradeHistory {
            get {
                return ResourceManager.GetString("GradeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Lab.
        /// </summary>
        public static string IndividualLab {
            get {
                return ResourceManager.GetString("IndividualLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Lab Report.
        /// </summary>
        public static string IndividualLabReport {
            get {
                return ResourceManager.GetString("IndividualLabReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab ID.
        /// </summary>
        public static string LabID {
            get {
                return ResourceManager.GetString("LabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Result.
        /// </summary>
        public static string LabResult {
            get {
                return ResourceManager.GetString("LabResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCL.
        /// </summary>
        public static string LCL {
            get {
                return ResourceManager.GetString("LCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID.
        /// </summary>
        public static string LocationID {
            get {
                return ResourceManager.GetString("LocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as : .
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA List by Location.
        /// </summary>
        public static string NAListByLocation {
            get {
                return ResourceManager.GetString("NAListByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NND.
        /// </summary>
        public static string NND {
            get {
                return ResourceManager.GetString("NND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NND Result.
        /// </summary>
        public static string NNDResult {
            get {
                return ResourceManager.GetString("NNDResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not Authorized to Perform this Action.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Outstanding CARs.
        /// </summary>
        public static string NumberOustandingCARs {
            get {
                return ResourceManager.GetString("NumberOustandingCARs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Summary Report.
        /// </summary>
        public static string PerformanceSummaryReport {
            get {
                return ResourceManager.GetString("PerformanceSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Lab.
        /// </summary>
        public static string PleaseSelectLab {
            get {
                return ResourceManager.GetString("PleaseSelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Problematic Test.
        /// </summary>
        public static string PossibleProblematicTest {
            get {
                return ResourceManager.GetString("PossibleProblematicTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Date.
        /// </summary>
        public static string PostedDate {
            get {
                return ResourceManager.GetString("PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Area Access.
        /// </summary>
        public static string ProgramAreaAccess {
            get {
                return ResourceManager.GetString("ProgramAreaAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Assignment.
        /// </summary>
        public static string ProgramAssignment {
            get {
                return ResourceManager.GetString("ProgramAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program ID.
        /// </summary>
        public static string ProgramID {
            get {
                return ResourceManager.GetString("ProgramID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs By Sponsor.
        /// </summary>
        public static string ProgramsBySponsor {
            get {
                return ResourceManager.GetString("ProgramsBySponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Setup.
        /// </summary>
        public static string ProgramSetup {
            get {
                return ResourceManager.GetString("ProgramSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Report Grading.
        /// </summary>
        public static string QuarterlyReportGrading {
            get {
                return ResourceManager.GetString("QuarterlyReportGrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Summary.
        /// </summary>
        public static string QuarterlySummary {
            get {
                return ResourceManager.GetString("QuarterlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Posted Samples.
        /// </summary>
        public static string RecentPostedSamples {
            get {
                return ResourceManager.GetString("RecentPostedSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Tables.
        /// </summary>
        public static string ReferenceTables {
            get {
                return ResourceManager.GetString("ReferenceTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Finalize.
        /// </summary>
        public static string ReFinalize {
            get {
                return ResourceManager.GetString("ReFinalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestrictedUserDashboard.
        /// </summary>
        public static string RestrictedUserDashboard {
            get {
                return ResourceManager.GetString("RestrictedUserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Sample? All existing Lab Result data linked to this Sample will be deleted..
        /// </summary>
        public static string SampleDeletionWarning {
            get {
                return ResourceManager.GetString("SampleDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample ID.
        /// </summary>
        public static string SampleID {
            get {
                return ResourceManager.GetString("SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Processing.
        /// </summary>
        public static string SampleProcessing {
            get {
                return ResourceManager.GetString("SampleProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Of.
        /// </summary>
        public static string SatelliteOf {
            get {
                return ResourceManager.GetString("SatelliteOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save / Review.
        /// </summary>
        public static string SaveReview {
            get {
                return ResourceManager.GetString("SaveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lab.
        /// </summary>
        public static string SelectLab {
            get {
                return ResourceManager.GetString("SelectLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Labs.
        /// </summary>
        public static string SelectLabs {
            get {
                return ResourceManager.GetString("SelectLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Method.
        /// </summary>
        public static string SelectMethod {
            get {
                return ResourceManager.GetString("SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Selected.
        /// </summary>
        public static string SendSelected {
            get {
                return ResourceManager.GetString("SendSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Lab ID.
        /// </summary>
        public static string StaticLabID {
            get {
                return ResourceManager.GetString("StaticLabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std Dev.
        /// </summary>
        public static string StdDev {
            get {
                return ResourceManager.GetString("StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit For Approval.
        /// </summary>
        public static string SubmitForApproval {
            get {
                return ResourceManager.GetString("SubmitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User Dashboard.
        /// </summary>
        public static string SuperUserDashboard {
            get {
                return ResourceManager.GetString("SuperUserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Dashboard.
        /// </summary>
        public static string SysAdminDashboard {
            get {
                return ResourceManager.GetString("SysAdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Announcements.
        /// </summary>
        public static string SystemAnnouncements {
            get {
                return ResourceManager.GetString("SystemAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPU.
        /// </summary>
        public static string TPU {
            get {
                return ResourceManager.GetString("TPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Graphs / Queries.
        /// </summary>
        public static string TrendGraphs {
            get {
                return ResourceManager.GetString("TrendGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCL.
        /// </summary>
        public static string UCL {
            get {
                return ResourceManager.GetString("UCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update NA List.
        /// </summary>
        public static string UpdateNAList {
            get {
                return ResourceManager.GetString("UpdateNAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        public static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View List of all available Quarterly Reports.
        /// </summary>
        public static string ViewListQuarterlyReports {
            get {
                return ResourceManager.GetString("ViewListQuarterlyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-Score.
        /// </summary>
        public static string ZScore {
            get {
                return ResourceManager.GetString("ZScore", resourceCulture);
            }
        }
    }
}
