//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedDot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Area.
        /// </summary>
        internal static string AddArea {
            get {
                return ResourceManager.GetString("AddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit.
        /// </summary>
        internal static string AddCredit {
            get {
                return ResourceManager.GetString("AddCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reward.
        /// </summary>
        internal static string AddReward {
            get {
                return ResourceManager.GetString("AddReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Table.
        /// </summary>
        internal static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Payment.
        /// </summary>
        internal static string AdjustedPayment {
            get {
                return ResourceManager.GetString("AdjustedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Customers.
        /// </summary>
        internal static string AllCustomers {
            get {
                return ResourceManager.GetString("AllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Tech.
        /// </summary>
        internal static string AssignEmployee {
            get {
                return ResourceManager.GetString("AssignEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignGiftCard.
        /// </summary>
        internal static string AssignGiftCard {
            get {
                return ResourceManager.GetString("AssignGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Tip.
        /// </summary>
        internal static string AutoTip {
            get {
                return ResourceManager.GetString("AutoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Office.
        /// </summary>
        internal static string BackOffice {
            get {
                return ResourceManager.GetString("BackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call-In.
        /// </summary>
        internal static string CallIn {
            get {
                return ResourceManager.GetString("CallIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Discount.
        /// </summary>
        internal static string CashDiscount {
            get {
                return ResourceManager.GetString("CashDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier In Out.
        /// </summary>
        internal static string CashierInOut {
            get {
                return ResourceManager.GetString("CashierInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Register.
        /// </summary>
        internal static string CashRegister {
            get {
                return ResourceManager.GetString("CashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Tender.
        /// </summary>
        internal static string CashTender {
            get {
                return ResourceManager.GetString("CashTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Tendered.
        /// </summary>
        internal static string CashTendered {
            get {
                return ResourceManager.GetString("CashTendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Total.
        /// </summary>
        internal static string CashTotal {
            get {
                return ResourceManager.GetString("CashTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP.
        /// </summary>
        internal static string CCP {
            get {
                return ResourceManager.GetString("CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Due.
        /// </summary>
        internal static string ChangeDue {
            get {
                return ResourceManager.GetString("ChangeDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Order.
        /// </summary>
        internal static string ClearOrder {
            get {
                return ResourceManager.GetString("ClearOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In.
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Out.
        /// </summary>
        internal static string ClockOut {
            get {
                return ResourceManager.GetString("ClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Service.
        /// </summary>
        internal static string CounterService {
            get {
                return ResourceManager.GetString("CounterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Admin.
        /// </summary>
        internal static string CreditCardAdmin {
            get {
                return ResourceManager.GetString("CreditCardAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C/C Surcharge.
        /// </summary>
        internal static string CreditCardSurcharge {
            get {
                return ResourceManager.GetString("CreditCardSurcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Date.
        /// </summary>
        internal static string CustomDate {
            get {
                return ResourceManager.GetString("CustomDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Admin.
        /// </summary>
        internal static string DatabaseAdmin {
            get {
                return ResourceManager.GetString("DatabaseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        internal static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine In.
        /// </summary>
        internal static string DineIn {
            get {
                return ResourceManager.GetString("DineIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive-Thru.
        /// </summary>
        internal static string DriveThru {
            get {
                return ResourceManager.GetString("DriveThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Combo.
        /// </summary>
        internal static string EditCombo {
            get {
                return ResourceManager.GetString("EditCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout.
        /// </summary>
        internal static string EditLayout {
            get {
                return ResourceManager.GetString("EditLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Portal.
        /// </summary>
        internal static string EmployeePortal {
            get {
                return ResourceManager.GetString("EmployeePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Finger Print.
        /// </summary>
        internal static string EnrollFingerPrint {
            get {
                return ResourceManager.GetString("EnrollFingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOD Settle.
        /// </summary>
        internal static string EODSettle {
            get {
                return ResourceManager.GetString("EODSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Refund.
        /// </summary>
        internal static string FullRefund {
            get {
                return ResourceManager.GetString("FullRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Store Credit.
        /// </summary>
        internal static string FullStoreCredit {
            get {
                return ResourceManager.GetString("FullStoreCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card.
        /// </summary>
        internal static string GiftCard {
            get {
                return ResourceManager.GetString("GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Certificate.
        /// </summary>
        internal static string GiftCertificate {
            get {
                return ResourceManager.GetString("GiftCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string Gratuity {
            get {
                return ResourceManager.GetString("Gratuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Total.
        /// </summary>
        internal static string LaborTotal {
            get {
                return ResourceManager.GetString("LaborTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Refund.
        /// </summary>
        internal static string ManualRefund {
            get {
                return ResourceManager.GetString("ManualRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Setup.
        /// </summary>
        internal static string MenuSetup {
            get {
                return ResourceManager.GetString("MenuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandise.
        /// </summary>
        internal static string Merchandise {
            get {
                return ResourceManager.GetString("Merchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max.
        /// </summary>
        internal static string MinMax {
            get {
                return ResourceManager.GetString("MinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        internal static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Seat.
        /// </summary>
        internal static string NewSeat {
            get {
                return ResourceManager.GetString("NewSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        internal static string NewTicket {
            get {
                return ResourceManager.GetString("NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sale.
        /// </summary>
        internal static string NoSale {
            get {
                return ResourceManager.GetString("NoSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        internal static string OpenOrders {
            get {
                return ResourceManager.GetString("OpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Pay.
        /// </summary>
        internal static string OtherPay {
            get {
                return ResourceManager.GetString("OtherPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Payments.
        /// </summary>
        internal static string OtherPayments {
            get {
                return ResourceManager.GetString("OtherPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Refund.
        /// </summary>
        internal static string PartialRefund {
            get {
                return ResourceManager.GetString("PartialRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Store Credit.
        /// </summary>
        internal static string PartialStoreCredit {
            get {
                return ResourceManager.GetString("PartialStoreCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Out.
        /// </summary>
        internal static string PayOut {
            get {
                return ResourceManager.GetString("PayOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Employee.
        /// </summary>
        internal static string PickEmployee {
            get {
                return ResourceManager.GetString("PickEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Name.
        /// </summary>
        internal static string PickName {
            get {
                return ResourceManager.GetString("PickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Auth.
        /// </summary>
        internal static string PreAuth {
            get {
                return ResourceManager.GetString("PreAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Override.
        /// </summary>
        internal static string PriceOverride {
            get {
                return ResourceManager.GetString("PriceOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Credit Slip.
        /// </summary>
        internal static string PrintCreditSlip {
            get {
                return ResourceManager.GetString("PrintCreditSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string Printers {
            get {
                return ResourceManager.GetString("Printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Receipt.
        /// </summary>
        internal static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Record.
        /// </summary>
        internal static string PrintRecord {
            get {
                return ResourceManager.GetString("PrintRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Reward.
        /// </summary>
        internal static string PrintReward {
            get {
                return ResourceManager.GetString("PrintReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Sales.
        /// </summary>
        internal static string PrintSales {
            get {
                return ResourceManager.GetString("PrintSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        internal static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Sales.
        /// </summary>
        internal static string QuickSales {
            get {
                return ResourceManager.GetString("QuickSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral.
        /// </summary>
        internal static string Referral {
            get {
                return ResourceManager.GetString("Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From.
        /// </summary>
        internal static string RemoveFrom {
            get {
                return ResourceManager.GetString("RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Setup.
        /// </summary>
        internal static string ReportSetup {
            get {
                return ResourceManager.GetString("ReportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Sales.
        /// </summary>
        internal static string RetailSales {
            get {
                return ResourceManager.GetString("RetailSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        internal static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Sales.
        /// </summary>
        internal static string SalonSales {
            get {
                return ResourceManager.GetString("SalonSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        internal static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Service.
        /// </summary>
        internal static string SearchService {
            get {
                return ResourceManager.GetString("SearchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        internal static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        internal static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle.
        /// </summary>
        internal static string Settle {
            get {
                return ResourceManager.GetString("Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettledOrders.
        /// </summary>
        internal static string SettledOrders {
            get {
                return ResourceManager.GetString("SettledOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Fee.
        /// </summary>
        internal static string ShopFee {
            get {
                return ResourceManager.GetString("ShopFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Combine.
        /// </summary>
        internal static string SplitCombine {
            get {
                return ResourceManager.GetString("SplitCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Card.
        /// </summary>
        internal static string StampCard {
            get {
                return ResourceManager.GetString("StampCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surcharge.
        /// </summary>
        internal static string Surcharge {
            get {
                return ResourceManager.GetString("Surcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Tab Customer.
        /// </summary>
        internal static string TabCustomer {
            get {
                return ResourceManager.GetString("TabCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Layout.
        /// </summary>
        internal static string TableLayout {
            get {
                return ResourceManager.GetString("TableLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Service.
        /// </summary>
        internal static string TableService {
            get {
                return ResourceManager.GetString("TableService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Exempt.
        /// </summary>
        internal static string TaxExempt {
            get {
                return ResourceManager.GetString("TaxExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Disc.
        /// </summary>
        internal static string TicketDisc {
            get {
                return ResourceManager.GetString("TicketDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Discount.
        /// </summary>
        internal static string TicketDiscount {
            get {
                return ResourceManager.GetString("TicketDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Card.
        /// </summary>
        internal static string TimeCard {
            get {
                return ResourceManager.GetString("TimeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Report.
        /// </summary>
        internal static string TimeReport {
            get {
                return ResourceManager.GetString("TimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipAmount.
        /// </summary>
        internal static string TipAmount {
            get {
                return ResourceManager.GetString("TipAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Go Orders.
        /// </summary>
        internal static string ToGo {
            get {
                return ResourceManager.GetString("ToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        internal static string TotalPayment {
            get {
                return ResourceManager.GetString("TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk-In.
        /// </summary>
        internal static string WalkIn {
            get {
                return ResourceManager.GetString("WalkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
