//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDotService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat2prod
    {
        public int id { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> prodid { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
    }
}
