//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDotService
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public category()
        {
            this.cat2prod = new HashSet<cat2prod>();
        }
    
        public int id { get; set; }
        public string colorcode { get; set; }
        public string lettercode { get; set; }
        public string description { get; set; }
        public string imagesrc { get; set; }
        public string cattype { get; set; }
        public Nullable<int> sortorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat2prod> cat2prod { get; set; }
    }
}
