//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDotService
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public int id { get; set; }
        public string customerid { get; set; }
        public string machineid { get; set; }
        public string application { get; set; }
        public string applevel { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string permission { get; set; }
        public System.DateTime createdate { get; set; }
        public string comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
