//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDotService
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public int salesid { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public string authorcode { get; set; }
        public decimal netamount { get; set; }
        public Nullable<int> voided { get; set; }
    
        public virtual sale sale { get; set; }
    }
}
