//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int id { get; set; }
        public Nullable<System.DateTime> apptdate { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> employeeid { get; set; }
        public Nullable<int> customerid { get; set; }
        public string note { get; set; }
        public string status { get; set; }
        public Nullable<int> catid { get; set; }
        public string servicelist { get; set; }
        public Nullable<bool> flexible { get; set; }
    }
}
