//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string displayname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public bool appointment { get; set; }
        public bool active { get; set; }
        public bool sales { get; set; }
        public int securitylevel { get; set; }
        public int commission { get; set; }
        public int paysplit { get; set; }
    }
}
