//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesitem
    {
        public int id { get; set; }
        public int salesid { get; set; }
        public string description { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> employeeid { get; set; }
        public string note { get; set; }
        public string commissiontype { get; set; }
        public string type { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string reportcategory { get; set; }
        public Nullable<decimal> commissionamt { get; set; }
        public Nullable<decimal> supplyfee { get; set; }
        public Nullable<decimal> turnvalue { get; set; }
        public Nullable<decimal> rewardamount { get; set; }
        public Nullable<int> rewardexception { get; set; }
    
        public virtual sale sale { get; set; }
    }
}
