//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storeEntities : DbContext
    {
        public storeEntities(string connectionstring)
            : base("name=storeEntities")
        {
            if (connectionstring != "") this.Database.Connection.ConnectionString = connectionstring;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<cat2prod> cat2prod { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<gratuity> gratuities { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<salesitem> salesitems { get; set; }
        public virtual DbSet<SysUserType> SysUserTypes { get; set; }
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
    }
}
