//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysSetting
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string Description1 { get; set; }
        public string Value1 { get; set; }
        public string Description2 { get; set; }
        public string Value2 { get; set; }
        public string Description3 { get; set; }
        public string Value3 { get; set; }
        public string Description4 { get; set; }
        public string Value4 { get; set; }
        public string Description5 { get; set; }
        public string Value5 { get; set; }
        public string Description6 { get; set; }
        public string Value6 { get; set; }
        public string Description7 { get; set; }
        public string Value7 { get; set; }
        public string Description8 { get; set; }
        public string Value8 { get; set; }
        public string Description9 { get; set; }
        public string Value9 { get; set; }
        public string Description10 { get; set; }
        public string Value10 { get; set; }
    }
}
