//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cat2prod = new HashSet<cat2prod>();
        }
    
        public int id { get; set; }
        public string menuprefix { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string imagesrc { get; set; }
        public string type { get; set; }
        public string reportcategory { get; set; }
        public string commissiontype { get; set; }
        public string colorcode { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> supplyfee { get; set; }
        public Nullable<decimal> commissionamt { get; set; }
        public Nullable<decimal> turnvalue { get; set; }
        public Nullable<bool> taxable { get; set; }
        public Nullable<int> qoh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat2prod> cat2prod { get; set; }
    }
}
