//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsreply
    {
        public int id { get; set; }
        public string api_id { get; set; }
        public string fromphone { get; set; }
        public string tophone { get; set; }
        public string replytimestamp { get; set; }
        public string replytext { get; set; }
    }
}
